Update README.md
forzagreen/n2words pull request #66
Opened 2022-03-25 00:32 UTC by TylerVigario

Thought to rewrite the package summary and updated a few other things as well. Open to suggestions, thanks for review!

2022-03-25 13:57 UTC, forzagreen requested changes
Nice 👍

2022-03-25 13:57 UTC, forzagreen commented on README.md
> +n2words is a library that converts a numerical number into an written number. We have support for multiple languages (25 and growing) and our package is lightweight, modular, and has minimal dependec
```suggestion
n2words is a library that converts a numerical number into a written number. We have support for multiple languages (25 and growing) and our package is lightweight, modular, and has minimal dependencies.
```

2022-03-26 21:50 UTC, TylerVigario commented on README.md
> +n2words is a library that converts a numerical number into an written number. We have support for multiple languages (25 and growing) and our package is lightweight, modular, and has minimal dependec
Thanks, committed changes

2022-03-27 08:57 UTC, forzagreen approved these changes

2022-03-27 08:57 UTC, merged